#
# This file is part of Astarte.
#
# Copyright 2020 Ispirata Srl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: "Operator e2e tests"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        testSuite:
        - "010"
        - "011"
        - "10"
        kubernetesNodeImage:
        - "kindest/node:v1.16.9@sha256:7175872357bc85847ec4b1aba46ed1d12fa054c83ac7a8a11f5c268957fd5765"
        - "kindest/node:v1.17.5@sha256:ab3f9e6ec5ad8840eeb1f76c89bb7948c77bbf76bcebe1a8b59790b8ae9a283a"
        - "kindest/node:v1.18.2@sha256:7b27a6d0f2517ff88ba444025beae41491b016bc6af573ba467b70c5e8e0d85f"
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        # Ensure we're on Go 1.14
        go-version: '1.14.x'
    - uses: engineerd/setup-kind@v0.3.0
      with:
        version: "v0.8.1"
        image: "${{ matrix.kubernetesNodeImage }}"
    # Download Operator SDK binary
    - name: Download Operator SDK
      run: |
        curl -L -o operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.17.0/operator-sdk-v0.17.0-x86_64-linux-gnu
        chmod +x operator-sdk
    - name: Ensure KinD is up
      run: |
        kubectl cluster-info
        kubectl get pods -n kube-system
    - name: Setup needed resources
      run: |
        kubectl create namespace astarte-test
        kubectl apply -f deploy/service_account.yaml
        kubectl apply -f deploy/role.yaml
        kubectl apply -f deploy/role_binding.yaml
        kubectl create -f deploy/crds/api.astarte-platform.org_astartes_crd.yaml
        kubectl create -f deploy/crds/api.astarte-platform.org_astartevoyageringresses_crd.yaml
        kubectl create -f deploy/crds/api.astarte-platform.org_flows_crd.yaml
    - name: Run e2e tests
      run: ./operator-sdk test local ./test/e2e${{ matrix.testSuite }} --go-test-flags "-v -timeout 30m" --operator-namespace kube-system --watch-namespace astarte-test --up-local --no-setup
    - name: Dump debug info
      if: failure()
      run: |
        kubectl get pods -n astarte-test
        kubectl get deployment -n astarte-test
        kubectl get statefulset -n astarte-test
        kubectl get secrets -n astarte-test
        kubectl get configmaps -n astarte-test
        kubectl get pvc -n astarte-test
        kubectl describe astarte -n astarte-test || echo "Astarte already deleted"
        kubectl logs -n astarte-test example-astarte-vernemq-0 || echo "No logs"
        kubectl logs -n astarte-test example-astarte-vernemq-0 --previous || echo "No logs"
        kubectl logs -n astarte-test deployment/example-astarte-flow || echo "No logs"
        kubectl logs -n astarte-test deployment/example-astarte-flow --previous || echo "No logs"
    - name: Show pod states
      run: |
        kubectl get pods -n astarte-test
